spring.application.name=api-gateway
server.port=8000

#routes configuration

spring.cloud.gateway.server.webflux.routes[0].id=ROOM-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:1111
#spring.cloud.gateway.server.webflux.routes[0].uri=http://10.32.44.55:1111
#spring.cloud.gateway.server.webflux.routes[0].uri=lb://ROOM-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path= /api/v1/rooms/**

spring.cloud.gateway.server.webflux.routes[1].id=USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:2222
#spring.cloud.gateway.server.webflux.routes[1].uri=http://10.32.44.55:2222
#spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path= /api/v1/users/**, /api/v1/bookings/**

spring.cloud.gateway.server.webflux.routes[2].id=PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:3333
#spring.cloud.gateway.server.webflux.routes[2].uri=http://10.32.44.55:3333
#spring.cloud.gateway.server.webflux.routes[2].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path= /api/v1/payments/**, /api/v1/invoices/**

spring.cloud.gateway.server.webflux.routes[3].id=COMPLAINT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:4444
#spring.cloud.gateway.server.webflux.routes[3].uri=http://10.32.44.55:4444
#spring.cloud.gateway.server.webflux.routes[3].uri=lb://COMPLAINT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path= /api/v1/complaints/**

eureka.client.server-url.defaultZone=http://localhost:8761/eureka/
